site_name: 张 凯
site_url: https://bibaijin.github.io/homepage
site_description: 张凯的主页
site_author: bibaijin

repo_url: https://github.com/bibaijin/homepage

pages:
    - 主页: index.md
    - 技术:
        - haskell.md
        - LaTeX.md
        - python.md
        - shell.md
        - linux.md
    - 人文:
        - 西方伦理学史.md
    - 关于: about.md

theme: bootstrap

copyright: Copyright &copy; 2015 <a href="mailto:kaizhang91@163.com">张 凯</a>.
