site_name: 张 凯
site_url: https://bibaijin.github.io/homepage
site_description: 张凯的主页
site_author: bibaijin

repo_url: https://github.com/bibaijin/homepage

theme: mkdocs
theme_dir: 'custom_theme'

pages:
- 主页: index.md
- 人文:
    - 西方伦理学史: humanity/西方伦理学史.md
- 关于: about.md

markdown_extensions:
    - smarty
    - sane_lists
    - footnotes

copyright: Copyright &copy; 2015 <a href="mailto:bibaijin@gmail.com">张 凯</a>.
